blog/urls.py
from django.urls import path 
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category_list, name='category_list'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('search/', views.search, name='search'),
    path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
    # path('about', views.about, name="about"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path  # 这里引入include()方法
from django.conf import settings
from django.conf.urls.static import static
from utils.upload import upload_file   # 富文本编辑器上传图片方法


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls')),

    path('uploads/', upload_file, name='uploads')   # 上传图片url

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # 配置静态文件url


# 配置用户上传文件url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Stellaris的管理后台"
admin.site.index_title = "Stellaris管理后台"
admin.site.site_title = "Stellaris管理员登陆了"

blog/models.py
"""


"""
from django.db import models
from django.contrib.auth.models import User
from django.utils.functional import cached_property  # 缓存装饰器
from django.template.loader import render_to_string  # 渲染模板


class Category(models.Model):
    """ 博客的分类模型 """
    name = models.CharField(max_length=32, verbose_name="分类名称")
    desc = models.TextField(max_length=200, blank=True, default="", verbose_name="分类描述")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "博客分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

# 文章标签
class Tag(models.Model):
    name = models.CharField(max_length=10, verbose_name="文章标签")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

# 文章
class Post(models.Model):
    title = models.CharField(max_length=61, verbose_name="文章标题")
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name="文章描述")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    content = models.TextField(verbose_name="文章详情")
    tags = models.ForeignKey(Tag, blank=True, null=True, on_delete=models.CASCADE, verbose_name="文章标签")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="作者")
    is_hot = models.BooleanField(default=False, verbose_name="是否热门")   # 手动热门推荐

    pv = models.IntegerField(default=0,verbose_name="浏览量")  # 浏览量
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

# 侧边栏的模型数据
class Sidebar(models.Model):
    STATUS = (
        (1, '隐藏'),
        (2, '展示')
    )

    DISPLAY_TYPE = (
        (1, '搜索'),
        (2, '最新文章'),
        (3, '最热文章'),
        (4, '最近评论'),
        (5, '文章归档'),
        (6, 'HTML')
    )

    title = models.CharField(max_length=50, verbose_name="模块名称")  #  模块名称
    display_type = models.PositiveIntegerField(default=1, choices=DISPLAY_TYPE, verbose_name="展示类型")   # 侧边栏  搜索框/最新文章/热门文章/HTML自定义等
    content = models.CharField(max_length=500, blank=True, default='', verbose_name="内容",
                               help_text="如果设置的不是HTML类型，可为空")  # 这个字段是专门用来给HTML类型用的，其他类型可为空
    sort = models.PositiveIntegerField(default=1,  verbose_name="排序", help_text='序号越大越靠前')
    status = models.PositiveIntegerField(default=2, choices=STATUS, verbose_name="状态")        # 隐藏  显示状态
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")  # 时间

    class Meta:
        verbose_name = "侧边栏"
        verbose_name_plural = verbose_name
        ordering = ['-sort']

    def __str__(self):
        return self.title

    @classmethod    # 类方法装饰器，这个就变成了这个类的一个方法可以调用
    def get_sidebar(cls):
        return cls.objects.filter(status=2)   # 查询到所有允许展示的模块

    
    @property    # 成为一个类属性，调用的时候不需要后边的（）,是只读的，用户没办法修改
    def get_content(self):
        if self.display_type == 1:
            context = {

            }
            return render_to_string('blog/sidebar/search.html', context=context)
        elif self.display_type == 2:
            context = {
                
            }
            return render_to_string('blog/sidebar/new_post.html', context=context)
        elif self.display_type == 3:
            context = {

            }
            return render_to_string('blog/sidebar/hot_post.html', context=context)
        elif self.display_type == 4:  
            context = {

            }
            return render_to_string('blog/sidebar/commment.html', context=context)
        elif self.display_type == 5:   # 文章归档
            context = {

            }
            return render_to_string('blog/sidebar/archives.html', context=context)
        elif self.display_type == 6:   # 自定义侧边栏
           
            return self.content   # 在侧边栏直接使用这里的html，模板中必须使用safe过滤器去渲染HTML

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, F
from django.core.paginator import Paginator
# Create your views here.
from .models import Category, Post

# 首页
def index(request):
    post_list = Post.objects.all()   # 查询到所有的文章,queryset
    # 分页方法
    paginator = Paginator(post_list, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get("page")   # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}
    return render(request, "blog/index.html", context)

# 
def category_list(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    # 获取当前分类下的所有文章
    posts = category.post_set.all()
    paginator = Paginator(posts, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')   # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {'category': category, 'page_obj': page_obj }
    return render(request, 'blog/list.html', context)


def post_detail(request, post_id):
    # 文章详情页
    post = get_object_or_404(Post, id=post_id)

    # 用文章id来实现的上下篇
    prev_post = Post.objects.filter(id__lt=post_id).last()  # 上一篇
    next_post = Post.objects.filter(id__gt=post_id).first() # 下一篇
    Post.objects.filter(id=post_id).update(pv = F('pv') + 1)   # 这个功能有漏洞，仅做思路讲解
    
    # 用发布日期来实现上下篇
    # date_prev_post = Post.objects.filter(add_date__lt=post.add_date).last()
    # date_next_post = Post.objects.filter(add_date__gt=post.add_date).first()

    context = {'post': post, 'prev_post': prev_post, 'next_post': next_post}
    return render(request, 'blog/detail.html', context)


def search(request):
    """ 搜索视图 """
    keyword = request.GET.get('keyword')
    # 没有搜索默认显示所有文章
    if not keyword:
        post_list = Post.objects.all()
    else:
        # 包含查询的方法，用Q对象来组合复杂查询，title__icontains 他两个之间用的是双下划线（__）链接
        post_list = Post.objects.filter(Q(title__icontains=keyword) | Q(desc__icontains=keyword) | Q(content__icontains=keyword))
    paginator = Paginator(post_list, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')   # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'blog/index.html', context )


def archives(request, year, month):
    # 文章归档列表页
    post_list = Post.objects.filter(add_date__year=year, add_date__month=month)
    paginator = Paginator(post_list, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')   # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj, 'year': year, 'month': month}
    return render(request, 'blog/archives_list.html', context )

def about(request):
    return render(request, 'blog/about.html')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block section %}

{% endblock %}

blog/templates/blog/archives_list.html
{% extends 'blog/base.html' %}

{% block title %} {{ year }}{{ month }}的归档{% endblock %}

{% block archives %}
    <!-- 显示当前分类模块 -->
    <div class="box">
        每月归档：{{ year }}年{{ month }}月
        <div class="tags has-addons is-pulled-right">
          <span class="tag">共</span>
          <span class="tag is-primary">{{ post_list.count }} 篇</span>
        </div>
    </div>
    <!-- 显示当前分类模块 end-->
{% endblock  %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static category %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}博客首页{% endblock %}</title>
	<link rel="icon" href="{% static 'users/images/Stellaris.png' %}" type="image/x-icon">
	
	<link rel="stylesheet" href="{% static 'users/css/bulma.min.css' %}">
	<link rel="stylesheet" href="{% static 'users/css/move-menu.css' %}" />
    <link rel="stylesheet" href="{% static 'users/font/iconfont.css' %}" />
    <link rel="stylesheet" href="{% static 'users/font1/iconfont.css' %}" />
	
	<link rel="stylesheet" href="{% static 'users/css/view-line.css' %}" />
	<link rel="stylesheet" href="{% static 'users/css/top-menu.css' %}" />

	<link rel="stylesheet" href="{% static 'users/css/mainsection.css' %}" />
	
	<script type="text/javascript" src="{% static 'users/js/view-line.js' %}"></script>
</head>
<body>
	<!--顶部浏览条-->
	<progress id="content_progress" value="0"></progress>
	<!--顶部固定菜单栏-->
	<div class="top-menu">
		<a href="/"><h1 class="logo">Stellaris<span>blog.</span></h1></a>
		{% if user.is_authenticated %}<!-- 已登录 -->
			<ul>
				<li><a href="./friend-link.html">友链</a></li>
				<li><a href="#">分类</a>
					<div class="dropdown-menu">
						<ul>
							<!-- 获取分类列表 -->
							{% get_category_list as category_list %}
							{% for category in category_list %}
								<li><a href="{% url 'blog:category_list' category.id %}">
									{{ category.name }}
								</a></li>
							{% endfor %}
						</ul>
					</div>
				</li>
				<li><a href="">关于网站</a></li>
			</ul>
		{% else %}<!-- 未登录 -->
			<div class="buttons">
				<a class="button is-primary" href="{% url 'users:register' %}" target="_blank">
					<strong>注册</strong>
				</a>
				<a class="button is-light" href="{% url 'users:login' %}" target="_blank">
					登录
				</a>
			</div>
		{% endif %}
	</div>

	{% if user.is_authenticated %}
		<!--侧边固定人物信息栏目-->
		<div class="move-menu">
			<div class="point">
				<div class="point-item"> </div>
				<div class="point-item"> </div>
				<div class="point-item"> </div>
			</div>
			<!--头像-->
			<div class="icon">
				<div class="icon-img">
					<img src="{% static 'users/images/headimg.jpg' %}" alt="" />
				</div>
				<div class="icon-con">
					<username>{{ request.user.username }}</username><br>
					<introduction>{{ user.userprofile.gexing }}</introduction>
				</div>
			</div>
			<div class="cutoff-line"></div>
			<div class="info">
				<div class="box1">
					<p>129</p>
					粉丝
				</div>
				<div class="box2">
					<p>19</p>
					关注
				</div>
				<div class="box3">
					<p>55</p>
					收藏
				</div>
			</div>
			<div class="cutoff-line"></div>
			<div class="main">
				<a class="item" href="{% url 'users:user_profile' %}" target="_blank">
					<div class="light"></div>
					<div class="licon"><span class="iconfont icon-wenjian"></span></div>
					<div class="con">个人信息</div>
				</a>
				<div class="item">
					<div class="light"></div>
					<div class="licon"><span class="iconfont icon-xiaolian"></span></div>
					<div class="con">好友列表</div>
				</div>
				<!-- <div class="item" onclick="window.open('background-postmanagement.html')">
					<div class="light"></div>
					<div class="licon"><span class="iconfont icon-wenjian1"></span></div>
					<div class="con">文章管理</div>
				</div> -->
				<div class="item" onclick="window.open('selfinfo-myfavorite.html','_parent')">
					<div class="light"></div>
					<div class="licon"><span class="iconfont icon-shexiang"></span></div>
					<div class="con">我的收藏</div>
				</div>
				<div class="item">
					<div class="light"></div>
					<div class="licon"><span class="iconfont icon-qipao1"></span></div>
					<div class="con">网站反馈</div>
				</div>
				<a class="item" href="{% url 'admin:index' %}" target="_blank">
					<div class="light"></div>
					<div class="licon"><span class="iconfont icon-shexiang1"></span></div>
					<div class="con">后台(管理员)</div>
				</a>
			</div>
			<div class="cutoff-line"></div>
			<!-- <div class="title">
				<p>Sever 6</p>
			</div> -->
			<div class="main">
				<div class="item">
					<div class="licon"><span class="iconfont icon-sousuo"></span></div>
					<div class="con">查找</div>
				</div>
				<div class="item">
					<div class="licon"><span class="iconfont icon-caidan"></span></div>
					<div class="con">应用库</div>
				</div>
				<div class="item">
					<div class="licon"><span class="iconfont icon-renqun"></span></div>
					<div class="con">设置</div>
				</div>
				<div class="item" onclick="window.open('index.html','_parent')">
					<div class="licon"><span class="iconfont icon-gengduo-a"></span></div>
					<div class="con"><a href="{% url 'users:logout' %}">退出登录</a></div>
					
				</div>
			</div>
		</div>
	{% else %}
		<!--侧边固定人物信息栏目-->
		<div class="move-menu">
			<div class="point">
				<div class="point-item"> </div>
				<div class="point-item"> </div>
				<div class="point-item"> </div>
			</div>
			<!--头像-->
			<div class="icon">
				<div class="icon-img"><img src="{% static 'users/images/headimg.jpg' %}" alt="" /></div>
				<div class="icon-con">
					<username>请登录</username><br>
					<introduction>右上角(注册/登录)</introduction>
				</div>
			</div>
		</div>
	{% endif %}
	<!--页面内容-->
	<video src="{% static 'users/images/linmeng.mp4' %}" class="background" autoplay loop muted></video>
	<div class="mainsection">
		<div class="top">
			<div class="blog">
				{% block section %}
					{% block archives %}<!-- 这里可以拿来写公告 -->{% endblock  %}
					{% if page_obj %} <!-- 如果存在文章 -->
						{% for post in page_obj %} <!-- 遍历加载 -->
							<div class="box_">
								<h1>
									<a href="{% url 'blog:post_detail' post.id %}"> {{ post.title }}</a>
								</h1>
								<span>作者：{{ post.owner }}</span> <span>发布日期：{{ post.add_date }}</span>
								<!-- https://docs.djangoproject.com/zh-hans/3.2/ref/templates/builtins/#truncatechars  官方文档 -->
								<p>{{ post.desc|truncatechars:200 }}</p>
							</div>
							<div class="blog-gap"></div>
						{% endfor %}
					{% else %}
						<div class="box_">
							<p>文章不存在！</p>
						</div>
					{% endif %}
					
					{% if page_obj %}
						<nav class="pagination is-centered" role="navigation" aria-label="pagination">
							{% if page_obj.has_previous %}
								<a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
							{% endif %}

							{% if page_obj.has_next %}
							<a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
							{% endif %}

							<ul class="pagination-list">
								{% if page_obj.has_previous %}
									<li><a class="pagination-link" aria-label="Goto page 45" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
								{% endif %}
									<li><a class="pagination-link is-current" aria-label="Page {{ page_obj.number }}" aria-current="page" href='?page={{ page_obj.number }}'>{{ page_obj.number }}</a></li>
								{% if page_obj.has_next %}
									<li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}" aria-label="Goto page {{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
								{% endif %}
							</ul>
						</nav>
					{% endif %}
				{% endblock %}
			</div>
			<div class="sidebar">
				{% block right %}
					{% get_sidebar_list as sidebar_list %}
					{% for sidebar in sidebar_list %}
					<div class="box">
						<h1 class=" is-size-5 title">{{ sidebar.title }}</h1>
						<p>{{ sidebar.get_content|safe }}</p>
					</div>
					{% endfor %}
				{% endblock %}
			</div>
		</div>
		{% block footer %}
			<div class="bottom">
				Copyright © by LIJUNLIN All Rights Reserved.<br>
				粤ICP备2022020312号-1
			</div>
		{% endblock %}
	</div>
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block section %}
    <div class="box_">
        <h1 class="is-size-5 has-text-weight-bold">
            <a> {{ post.title }}</a>
        </h1>
        <div class=" is-size-7 has-text-grey-light pt-1 pb-1">
            <span class="mr-3">作者：{{ post.owner }}</span> <span>发布日期：{{ post.add_date }}</span> <span>浏览量：{{ post.pv }}</span>
        </div>
        <div class="content">
            {{ post.content|safe }}
        </div>
    </div>

    <div class="box">
        <div class="level">
            <div class="level-left">
                {% if prev_post %}
                <span>上一篇：</span><a href="{% url 'blog:post_detail' prev_post.id %}" class="level-item">{{ prev_post.title }}</a>
                {% else %}
                <span class=" has-text-danger-dark is-size-7">无上一篇</span>
                {% endif %}
            </div>
            <div class="level-right">
                {% if next_post %}
                <span>下一篇：</span><a href="{% url 'blog:post_detail' next_post.id %}" class="level-item">{{ next_post.title }}</a>
                {% else %}
                <span class=" has-text-danger-dark is-size-7">已经是最后一篇</span>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

blog/templates/blog/list.html
{% extends 'blog/base.html' %}